# Q1- construct 1d numpy array, 2d numpy array,3d numpy array.

In [1]:
import numpy as np

a1D = np.array([1, 2, 3, 4])
a2D = np.array([[1, 2], [3, 4]])
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Q2- Write a NumPy program to test whether any of the elements of a given array is non-zero. Hint use any()

In [2]:
x = np.array([1, 1, 0, 0])
print("Original array: ", x)
print("Test if any element is non-zero: ",np.any(x))


x = np.array([0, 0, 0, 0])
print("Original array:",x)
print("Test if any element is non-zero: ", np.any(x))

Original array:  [1 1 0 0]
Test if any element is non-zero:  True
Original array: [0 0 0 0]
Test if any element is non-zero:  False


# Q3- Write a NumPy program to create an array of 10 zeros, 10 ones, 10 fives.

In [3]:
array=np.zeros(10)
print(array)

array=np.ones(10)
print(array)

array=np.ones(10)*5
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


# Q4- Write a NumPy program to create an array of 10 zeros 3d

In [4]:
N = 3
np.zeros((N,)*3)

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

# Q5- Write a NumPy program to create an array of the integers from 30 to 70.

In [5]:
array = np.arange(30,71)
print(array)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


# Q6- Write a NumPy program to create a 3x3 identity matrix.

In [6]:
arr = np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Q7- Write a NumPy program to generate a random number between 0 and 1.

In [7]:
random_num = np.random.random(1)[0]
print(random_num)

0.32784466257300804


# Q8- Write a NumPy program to create a 3X4 array using and iterate over it.

In [8]:
a = np.arange(10,22).reshape((3, 4))
print(a)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [9]:
for x in np.nditer(a):
  print(x,end=" ")

10 11 12 13 14 15 16 17 18 19 20 21 

# Q9- Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.

In [10]:
x = np.ones((10, 10))
x[1:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
